version: '3'
services:
  rioproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - jenkins_data:/var/lib/jenkins
    networks:
      - app-network

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - app-network

  eclipse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:1
    ports:
      - 8081:8081
      - 5901:5901
    volumes:
      - workspace:/workspace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_data:
  workspace:
