version: '3'
services:
  rioproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8081
    volumes:
      - jenkins_data:/var/lib/jenkins
    networks:
      - app-network

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8084
    networks:
      - app-network

eclipse:
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - DISPLAY=:1
  ports:
    - 5901:5901
  volumes:
    - workspace:/workspace
  networks:
    - app-network
  command:
    - "/usr/bin/Xvfb"
    - ":1"
    - "-screen"
    - "0"
    - "1024x768x24"
    - "/opt/eclipse/eclipse"
    - "-data"
    - "/workspace"


networks:
  app-network:
    driver: bridge

volumes:
  jenkins_data:
  workspace:
